version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build command completed successfully!!
artifacts:
  files:
    - target/joinus-1.0.0.jar
  discard-paths: yes
