cloud:
  aws:
    credentials:
      access-key: asdas
      secret-key: 1233213
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: joinusstorage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB